
services:
  fakedata:
    container_name: postgre-fakedb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: fakedata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

networks:
  default:
    name: postgre-service_default
